imports:
    - { resource: services_core.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
