services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Controllers as services (only in test env).
    App\Tests\Fixtures\Controller\:
        resource: '../tests/Fixtures/Controller/'
        tags: ['controller.service_arguments']

    App\Tests\Fixtures\Service\:
        resource: '../tests/Fixtures/Service/'
